{% set version = "0.4.0" %}
{% set name = "s3fs" %}
{% set sha256 = "504a41ecb9edf0bd7798847b61839954e50508c5235ec7ee48c539ce46b4fa18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - python >=3.5
    - setuptools
    - boto3
    - pip

  run:
    - python >=3.5
    - boto3
    - fsspec >=0.6.0


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Convenient Filesystem interface over S3'
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
